//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UI", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me next time (uncheck if you are on shared computer).
        /// </summary>
        internal static string pages_account_login_checkbox_text_0000 {
            get {
                return ResourceManager.GetString("pages_account_login_checkbox_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string pages_account_login_label_text_0000 {
            get {
                return ResourceManager.GetString("pages_account_login_label_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string pages_account_login_label_text_0001 {
            get {
                return ResourceManager.GetString("pages_account_login_label_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string pages_account_login_localize_text_0000 {
            get {
                return ResourceManager.GetString("pages_account_login_localize_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this page..
        /// </summary>
        internal static string pages_account_login_localize_text_0001 {
            get {
                return ResourceManager.GetString("pages_account_login_localize_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div data-dialog-message=&quot;Access denied&quot;&gt;
        ///&lt;p&gt;&lt;b&gt;User cannot login.&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Invalid user name, password or account is blocked.&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string pages_account_login_login_failuretext_0000 {
            get {
                return ResourceManager.GetString("pages_account_login_login_failuretext_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is missing.
        /// </summary>
        internal static string pages_account_login_requiredfieldvalidator_errormessage_0000 {
            get {
                return ResourceManager.GetString("pages_account_login_requiredfieldvalidator_errormessage_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is missing.
        /// </summary>
        internal static string pages_account_login_requiredfieldvalidator_errormessage_0001 {
            get {
                return ResourceManager.GetString("pages_account_login_requiredfieldvalidator_errormessage_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string pages_account_login_title {
            get {
                return ResourceManager.GetString("pages_account_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div data-dialog-message=&quot;Password change failed&quot;&gt;
        ///&lt;p&gt;&lt;b&gt;Password cannot be changed.&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Old password is incorrect or new password does not meet the complexity requirements: Minimal length: {0}, non-alphanumeric characters required: {1}.&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string pages_account_password_changepassword_changepasswordfailuretext_0000 {
            get {
                return ResourceManager.GetString("pages_account_password_changepassword_changepasswordfailuretext_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation does not match.
        /// </summary>
        internal static string pages_account_password_comparevalidator_errormessage_0000 {
            get {
                return ResourceManager.GetString("pages_account_password_comparevalidator_errormessage_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password:.
        /// </summary>
        internal static string pages_account_password_label_text_0000 {
            get {
                return ResourceManager.GetString("pages_account_password_label_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        internal static string pages_account_password_label_text_0001 {
            get {
                return ResourceManager.GetString("pages_account_password_label_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation:.
        /// </summary>
        internal static string pages_account_password_label_text_0002 {
            get {
                return ResourceManager.GetString("pages_account_password_label_text_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed!.
        /// </summary>
        internal static string pages_account_password_localize_text_0000 {
            get {
                return ResourceManager.GetString("pages_account_password_localize_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is missing.
        /// </summary>
        internal static string pages_account_password_requiredfieldvalidator_errormessage_0000 {
            get {
                return ResourceManager.GetString("pages_account_password_requiredfieldvalidator_errormessage_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is missing.
        /// </summary>
        internal static string pages_account_password_requiredfieldvalidator_errormessage_0001 {
            get {
                return ResourceManager.GetString("pages_account_password_requiredfieldvalidator_errormessage_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string pages_account_password_title {
            get {
                return ResourceManager.GetString("pages_account_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string pages_admin_useredit_button_text_0000 {
            get {
                return ResourceManager.GetString("pages_admin_useredit_button_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this user is enabled.
        /// </summary>
        internal static string pages_admin_useredit_checkbox_text_0000 {
            get {
                return ResourceManager.GetString("pages_admin_useredit_checkbox_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this user is SEWEN Wiki administrator.
        /// </summary>
        internal static string pages_admin_useredit_checkbox_text_0001 {
            get {
                return ResourceManager.GetString("pages_admin_useredit_checkbox_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string pages_admin_useredit_label_text_0000 {
            get {
                return ResourceManager.GetString("pages_admin_useredit_label_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password: (leave empty when no change requested).
        /// </summary>
        internal static string pages_admin_useredit_label_text_0001 {
            get {
                return ResourceManager.GetString("pages_admin_useredit_label_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is invalid.
        /// </summary>
        internal static string pages_admin_useredit_regularexpressionvalidator_errormessage_0000 {
            get {
                return ResourceManager.GetString("pages_admin_useredit_regularexpressionvalidator_errormessage_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is missing.
        /// </summary>
        internal static string pages_admin_useredit_requiredfieldvalidator_errormessage_0000 {
            get {
                return ResourceManager.GetString("pages_admin_useredit_requiredfieldvalidator_errormessage_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string pages_admin_useredit_title {
            get {
                return ResourceManager.GetString("pages_admin_useredit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial password:.
        /// </summary>
        internal static string pages_admin_userlist_label_text_0000 {
            get {
                return ResourceManager.GetString("pages_admin_userlist_label_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div data-dialog-message=&quot;Information&quot;&gt;&lt;p&gt;User was created successfully.&lt;/p&gt;&lt;/div&gt;.
        /// </summary>
        internal static string pages_admin_userlist_literal_text_0000 {
            get {
                return ResourceManager.GetString("pages_admin_userlist_literal_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div data-dialog-message=&quot;Error&quot;&gt;&lt;p&gt;User was not created.&lt;/p&gt;&lt;p&gt;Error status returned by provider: &lt;code&gt;{0}&lt;/code&gt;.&lt;/p&gt;&lt;/div&gt;.
        /// </summary>
        internal static string pages_admin_userlist_literal_text_0001 {
            get {
                return ResourceManager.GetString("pages_admin_userlist_literal_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new user.
        /// </summary>
        internal static string pages_admin_userlist_localize_text_0000 {
            get {
                return ResourceManager.GetString("pages_admin_userlist_localize_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string pages_admin_userlist_localize_text_0001 {
            get {
                return ResourceManager.GetString("pages_admin_userlist_localize_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string pages_admin_userlist_localize_text_0002 {
            get {
                return ResourceManager.GetString("pages_admin_userlist_localize_text_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        internal static string pages_admin_userlist_localize_text_0003 {
            get {
                return ResourceManager.GetString("pages_admin_userlist_localize_text_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        internal static string pages_admin_userlist_localize_text_0004 {
            get {
                return ResourceManager.GetString("pages_admin_userlist_localize_text_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial password is missing.
        /// </summary>
        internal static string pages_admin_userlist_requiredfieldvalidator_errormessage_0000 {
            get {
                return ResourceManager.GetString("pages_admin_userlist_requiredfieldvalidator_errormessage_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string pages_admin_userlist_title {
            get {
                return ResourceManager.GetString("pages_admin_userlist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all versions of this page?.
        /// </summary>
        internal static string pages_history_hyperlink_confirm_0000 {
            get {
                return ResourceManager.GetString("pages_history_hyperlink_confirm_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all versions of page, except the most recent?.
        /// </summary>
        internal static string pages_history_hyperlink_confirm_0001 {
            get {
                return ResourceManager.GetString("pages_history_hyperlink_confirm_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to page.
        /// </summary>
        internal static string pages_history_hyperlink_text_0000 {
            get {
                return ResourceManager.GetString("pages_history_hyperlink_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this version of page?.
        /// </summary>
        internal static string pages_history_iconhyperlink_confirm_0000 {
            get {
                return ResourceManager.GetString("pages_history_iconhyperlink_confirm_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this version of page.
        /// </summary>
        internal static string pages_history_iconhyperlink_tooltip_0000 {
            get {
                return ResourceManager.GetString("pages_history_iconhyperlink_tooltip_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string pages_history_localize_text_0000 {
            get {
                return ResourceManager.GetString("pages_history_localize_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string pages_history_localize_text_0001 {
            get {
                return ResourceManager.GetString("pages_history_localize_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        internal static string pages_history_localize_text_0002 {
            get {
                return ResourceManager.GetString("pages_history_localize_text_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string pages_history_localize_text_0003 {
            get {
                return ResourceManager.GetString("pages_history_localize_text_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page history.
        /// </summary>
        internal static string pages_history_title {
            get {
                return ResourceManager.GetString("pages_history_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string pages_pageedit_label_text_0000 {
            get {
                return ResourceManager.GetString("pages_pageedit_label_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        internal static string pages_pageedit_localize_text_0000 {
            get {
                return ResourceManager.GetString("pages_pageedit_localize_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body is missing.
        /// </summary>
        internal static string pages_pageedit_requiredfieldvalidator_errormessage_0000 {
            get {
                return ResourceManager.GetString("pages_pageedit_requiredfieldvalidator_errormessage_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit page.
        /// </summary>
        internal static string pages_pageedit_title {
            get {
                return ResourceManager.GetString("pages_pageedit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string pages_pagenew_label_text_0000 {
            get {
                return ResourceManager.GetString("pages_pagenew_label_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body:.
        /// </summary>
        internal static string pages_pagenew_label_text_0001 {
            get {
                return ResourceManager.GetString("pages_pagenew_label_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is missing.
        /// </summary>
        internal static string pages_pagenew_requiredfieldvalidator_errormessage_0000 {
            get {
                return ResourceManager.GetString("pages_pagenew_requiredfieldvalidator_errormessage_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new page.
        /// </summary>
        internal static string pages_pagenew_title {
            get {
                return ResourceManager.GetString("pages_pagenew_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new page.
        /// </summary>
        internal static string pages_page_hyperlink_text_0000 {
            get {
                return ResourceManager.GetString("pages_page_hyperlink_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string pages_page_hyperlink_text_0001 {
            get {
                return ResourceManager.GetString("pages_page_hyperlink_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        internal static string pages_page_hyperlink_text_0002 {
            get {
                return ResourceManager.GetString("pages_page_hyperlink_text_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit page.
        /// </summary>
        internal static string pages_page_hyperlink_text_0003 {
            get {
                return ResourceManager.GetString("pages_page_hyperlink_text_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all versions of this page.
        /// </summary>
        internal static string pages_page_iconhyperlink_text_0000 {
            get {
                return ResourceManager.GetString("pages_page_iconhyperlink_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all versions, except current.
        /// </summary>
        internal static string pages_page_iconhyperlink_text_0001 {
            get {
                return ResourceManager.GetString("pages_page_iconhyperlink_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP: {0}.
        /// </summary>
        internal static string pages_page_info_ip {
            get {
                return ResourceManager.GetString("pages_page_info_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        internal static string pages_page_info_user {
            get {
                return ResourceManager.GetString("pages_page_info_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0:d} {0:T}.
        /// </summary>
        internal static string pages_page_info_version {
            get {
                return ResourceManager.GetString("pages_page_info_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        internal static string pages_page_localize_text_0000 {
            get {
                return ResourceManager.GetString("pages_page_localize_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified page was not found..
        /// </summary>
        internal static string pages_page_localize_text_0001 {
            get {
                return ResourceManager.GetString("pages_page_localize_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Embeddable Wiki Engine.
        /// </summary>
        internal static string pages_page_title {
            get {
                return ResourceManager.GetString("pages_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        internal static string pages_search_localize_text_0000 {
            get {
                return ResourceManager.GetString("pages_search_localize_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pages found..
        /// </summary>
        internal static string pages_search_localize_text_0001 {
            get {
                return ResourceManager.GetString("pages_search_localize_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query is missing.
        /// </summary>
        internal static string pages_search_requiredfieldvalidator_errormessage_0000 {
            get {
                return ResourceManager.GetString("pages_search_requiredfieldvalidator_errormessage_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string pages_search_title {
            get {
                return ResourceManager.GetString("pages_search_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powered by DEVeveryday.net.
        /// </summary>
        internal static string pages_site_master_footer {
            get {
                return ResourceManager.GetString("pages_site_master_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEWEN - Simple Embeddable Web Engine.
        /// </summary>
        internal static string pages_site_master_hyperlink_text_0000 {
            get {
                return ResourceManager.GetString("pages_site_master_hyperlink_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to home page.
        /// </summary>
        internal static string pages_site_master_hyperlink_tooltip_0000 {
            get {
                return ResourceManager.GetString("pages_site_master_hyperlink_tooltip_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string pages_site_master_iconhyperlink_confirm_0002 {
            get {
                return ResourceManager.GetString("pages_site_master_iconhyperlink_confirm_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string pages_site_master_iconhyperlink_text_0000 {
            get {
                return ResourceManager.GetString("pages_site_master_iconhyperlink_text_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string pages_site_master_iconhyperlink_text_0001 {
            get {
                return ResourceManager.GetString("pages_site_master_iconhyperlink_text_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string pages_site_master_iconhyperlink_text_0002 {
            get {
                return ResourceManager.GetString("pages_site_master_iconhyperlink_text_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string pages_site_master_iconhyperlink_text_0003 {
            get {
                return ResourceManager.GetString("pages_site_master_iconhyperlink_text_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        internal static string pages_site_master_loginname_formatstring_0000 {
            get {
                return ResourceManager.GetString("pages_site_master_loginname_formatstring_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin: &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        internal static string pages_site_master_loginname_formatstring_0001 {
            get {
                return ResourceManager.GetString("pages_site_master_loginname_formatstring_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes;No.
        /// </summary>
        internal static string _ConfirmButtons {
            get {
                return ResourceManager.GetString("_ConfirmButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string _ConfirmTitle {
            get {
                return ResourceManager.GetString("_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string _Insert {
            get {
                return ResourceManager.GetString("_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string _Submit {
            get {
                return ResourceManager.GetString("_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string _Update {
            get {
                return ResourceManager.GetString("_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B:Bold;I:Italic;U:Underline;S:Strikethrough;Sup:Superscript;Sub:Subscript;;H1:Heading 1;H2:Heading 2;H3:Heading 3;H4:Heading 4;H5:Heading 5;H6:Heading 6;;WikiLink:Link to Wiki Page;ExtLink:External Link (URL);;Ul:Bulleted List;Ol:Numbered List;;CodeBlock:Source code;;Preview:Preview.
        /// </summary>
        internal static string _WikiEditToolbar {
            get {
                return ResourceManager.GetString("_WikiEditToolbar", resourceCulture);
            }
        }
    }
}
